name: CI/CD Flask App

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Кэшируем зависимости (ускоряет сборку)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # 4️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Запускаем unit-тесты
      - name: Run tests
        run: |
          python -m unittest discover -p "test_*.py" -v

      # 6️⃣ Собираем Docker-образ
      - name: Build Docker image
        run: docker build -t flask-app:latest .

      # 7️⃣ Деплой на Render через API
      - name: Deploy to Render
        if: success()
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deploy on Render..."
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d '{}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
