name: learn-github-actions
on: [repository_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6.0.0
      - run: python3 -m pip install -r requirements.txt
      - run: echo "Hello, World!"
